application: item-catalog-1038
version: 1
runtime: python27
api_version: 1
threadsafe: yes

indexes:

# This index is for fast date access on a Session
- kind: Session
  ancestor: yes
  properties:
  - name: date

# This index is for fast duration access on a Session
- kind: Session
  ancestor: yes
  properties:
  - name: duration

# This index is for fast type and timeee access on a Session
- kind: Session
  ancestor: yes
  properties:
  - name: typeOfSession
  - name: time

handlers:       # static then dynamic

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /css
  static_dir: static/bootstrap/css

- url: /fonts
  static_dir: static/fonts

- url: /partials
  static_dir: static/partials

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always

- url: /tasks/send_confirmation_email
  script: main.app

- url: /crons/set_announcement
  script: main.app

- url: /_ah/spi/.*
  script: conference.api
  secure: always

libraries:

- name: webapp2
  version: latest

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest
